PROMPT  
PROMPT =======================================================
PROMPT Destruction des tables
PROMPT =======================================================

DROP TABLE dictionnaire_commun CASCADE CONSTRAINTS;
DROP TABLE cooccurrences CASCADE CONSTRAINTS;

PROMPT  
PROMPT =======================================================
PROMPT Création des tables
PROMPT =======================================================

CREATE TABLE dictionnaire_commun (
	id 		NUMBER 			GENERATED BY DEFAULT ON NULL AS IDENTITY,
	mot     VARCHAR2(25)    NOT NULL,
    
    CONSTRAINT pk_dictcom_id PRIMARY KEY(id),
	CONSTRAINT uc_dictcom_mot UNIQUE(mot)
);

CREATE TABLE cooccurrences (
	id_mot1		NUMBER		NOT NULL,
	id_mot2		NUMBER		NOT NULL,
	fenetre		NUMBER		NOT NULL,
	resultat	NUMBER		NOT NULL,
	
	CONSTRAINT pk_cooccurrences	PRIMARY KEY(id_mot1, id_mot2, fenetre)
);
